id = "sweet-dracula"
name = "Sweet Dracula"
version = "0.1.0"
schema_version = 1
authors = ["Armin Chanchian"]
description = "A cheerful dark blue theme with vibrant, contrasting syntax highlighting."
repository = "https://github.com/armync/ArminC-Sweet-Dracula-Zed/"